export const PERMISSIONS = {
  MANAGE_CHANNELS: "MANAGE_CHANNELS",
  MANAGE_ROLES: "MANAGE_ROLES",
  MANAGE_COMMUNITY: "MANAGE_COMMUNITY",
  VIEW_LOGS: "VIEW_LOGS",
  KICK: "KICK",
  BAN: "BAN",
  SEND_MESSAGES: "SEND_MESSAGES",
  SEND_LINKS: "SEND_LINKS",
  ATTACH_FILES: "ATTACH_FILES",
  MANAGE_MESSAGES: "MANAGE_MESSAGES",
  ADMINISTRATOR: "ADMINISTRATOR",
} as const;